source:
    third_party_source:
        filepath_regex: [".*/test/.*", ".*/demo/.*", ".*/auth/.*", ".*/crypto/.*", ".*/model/.*", ".*/internal/.*", ".*/event/.*",  ".*/transfer/.*", ".*/utils/.*", ".*COS.*"]
